"""
Jira catalog loader
===================
Reads jira_catalog.json (generated by jira_import.py) and exposes:
  • PORTALS            – list of portals → groups → request types → fields
  • CATALOG_TYPES      – dict {request_type_key: display_name}
  • CATALOG_FIELDS     – dict {request_type_key: [field dicts]}

The frontend consumes PORTALS (via /api/public/portals) to render the whole
help-center dynamically, so it mirrors Jira 1:1.
"""
import os
import json

_HERE = os.path.dirname(os.path.abspath(__file__))
_CATALOG_PATH = os.path.join(_HERE, "jira_catalog.json")

# Portals we don't want to surface to end users (test / migrated / internal)
_HIDDEN_PORTALS = {
    "opsgenie_migrated_incidents_28_05_2024_00_19",
    "test123",
    "it_assets",          # only has "Emailed request"
}

# Friendly icons per portal (Heroicons path data) — falls back to a default
PORTAL_ICONS = {
    "it_service_desk":             "desktop",
    "core_people_helpdesk":        "users",
    "contractual_people_helpdesk": "users",
    "people_help_desk_contractual":"users",
    "data_engineering":            "database",
    "platform_engineering":        "cube",
    "travel_desk":                 "globe",
}

# Portals that use the People dual-ticket (CPH + IT) creation flow
PEOPLE_PORTAL_IDS = {
    "core_people_helpdesk",
    "contractual_people_helpdesk",
    "people_help_desk_contractual",
}


def _load():
    if not os.path.exists(_CATALOG_PATH):
        return {"portals": []}
    with open(_CATALOG_PATH, encoding="utf-8") as fh:
        return json.load(fh)


_raw = _load()

PORTALS = [
    {
        **p,
        "icon": PORTAL_ICONS.get(p["id"], "desktop"),
        "is_people": p["id"] in PEOPLE_PORTAL_IDS,
    }
    for p in _raw.get("portals", [])
    if p["id"] not in _HIDDEN_PORTALS
]

CATALOG_TYPES = {}
CATALOG_FIELDS = {}
for _p in PORTALS:
    for _rt in _p.get("request_types", []):
        CATALOG_TYPES[_rt["key"]]  = _rt["name"]
        CATALOG_FIELDS[_rt["key"]] = _rt.get("fields", [])


def public_portals():
    """Return a lightweight portal tree for the public help center."""
    out = []
    for p in PORTALS:
        groups_order = []
        for rt in p["request_types"]:
            for g in (rt.get("groups") or []):
                if g not in groups_order:
                    groups_order.append(g)
        out.append({
            "id": p["id"],
            "name": p["name"],
            "icon": p["icon"],
            "is_people": p["is_people"],
            "groups": groups_order,
            "request_types": [
                {
                    "key": rt["key"],
                    "name": rt["name"],
                    "description": rt.get("description", ""),
                    "group": (rt.get("groups") or [None])[0],
                    "fields": rt.get("fields", []),
                }
                for rt in p["request_types"]
            ],
        })
    return out
